DIFF_NAMES = [
    '[Crude] Brt-Dub',
    '[Crude] Dated-Brt',
    '[Crude] Wti-Brt',
    '[FO] 0.5 EW',
    '[FO] 3.5Rdm-Brt',
    '[FO] 380 EW',
    '[FO] EU0.5-3.5Rdm',
    '[FO] EU0.5-Brt',
    '[FO] S0.5-Brt',
    '[FO] S0.5-S380',
    '[FO] S180-Brt',
    '[FO] S180-S380',
    '[FO] S380-Brt',
    '[IP] 92-380',
    '[IP] 92-S0.5',
    '[IP] 92-S10ppm',
    '[IP] Ebob-3.5Rdm',
    '[IP] Ebob-ICEGO',
    '[IP] RB-HO',
    '[IP] S10ppm-S0.5',
    '[Lights] 92 EW',
    '[Lights] Ebob-Brt',
    '[Lights] EU GasNap',
    '[Lights] FEI Propane-MOPJ Naph',
    '[Lights] MOPJ Naph-Brt',
    '[Lights] Naph EW',
    '[Lights] NWE Naph-Brt',
    '[Lights] NWE Propane-Naph',
    '[Lights] Rbob-Brt',
    '[Lights] Rbob-Ebob',
    '[Lights] S92-Brt',
    '[Lights] SG GasNap',
    '[Dist] GO EW',
    '[Dist] HO-Brt',
    '[Dist] HOGO',
    '[Dist] ICEGO-Brt',
    '[Dist] Jet diff',
    '[Dist] NWE Jet-Brt',
    '[Dist] Regrade',
    '[Dist] SGO-Brt',
    '[Dist] SKO-Brt',
    '[Dist] SKO-NWE Jet',

]

CONTRACTS = ['Jun25', 'Jul25', 'Aug25', 'Sep25', 'Oct25', 'Nov25', 'Dec25', 'Jan26']