DIFF_NAMES = [
    'Brt-Dub',
    'Dated-Brt',
    'Wti-Brt',
    '0.5 EW',
    '3.5Rdm-Brt',
    '380 EW',
    'EU0.5-3.5Rdm',
    'EU0.5-Brt',
    'S0.5-Brt',
    'S0.5-S380',
    'S180-Brt',
    'S180-S380',
    'S380-Brt',
    '92-380',
    '92-S0.5',
    '92-S10ppm',
    'Ebob-3.5Rdm',
    'Ebob-ICEGO',
    'RB-HO',
    'S10ppm-S0.5',
    '92 EW',
    'Ebob-Brt',
    'EU GasNap',
    'FEI Propane-MOPJ Naph',
    'MOPJ Naph-Brt',
    'Naph EW',
    'NWE Naph-Brt',
    'NWE Propane-Naph',
    'Rbob-Brt',
    'Rbob-Ebob',
    'S92-Brt',
    'SG GasNap',
    'GO EW',
    'HO-Brt',
    'HOGO',
    'ICEGO-Brt',
    'Jet diff',
    'NWE Jet-Brt',
    'Regrade',
    'SGO-Brt',
    'SKO-Brt',
    'SKO-NWE Jet',
]

CONTRACTS = ['Jun25', 'Jul25', 'Aug25', 'Sep25', 'Oct25', 'Nov25', 'Dec25', 'Jan26']